In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import time
from nltk.corpus import wordnet
import re
import enchant
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
filename = '../data/li_first100000.csv'
reviews = pd.read_csv(filename)

In [3]:
def isNaN(x):
    return str(x).lower() != 'nan'
index = reviews['text'].apply(isNaN)
np.where(index!=True)

(array([ 2532, 12316, 23081, 64585, 66768, 69637, 84423]),)

In [4]:
N=reviews.shape[0]
review2 = reviews.loc[:N, ['text', 'stars']]
review2 = review2[index]

In [5]:
def text_split(text):    
    return [word for word in text.split()]

In [6]:
X = review2['text']
y = review2['stars']
bow_transformer = CountVectorizer(analyzer=text_split).fit(X)
feature_name = bow_transformer.get_feature_names()

In [7]:
X_matrix = bow_transformer.transform(X)
XX_matrix = X_matrix.toarray()
X_dataframe = pd.DataFrame(XX_matrix)

In [8]:
filename = '../data/li_frequent.csv'
sum_col_total = pd.read_csv(filename, header=None)

In [9]:
sum_col_total = np.array(sum_col_total).T
sum_col_total = sum_col_total[0]

In [10]:
sum_col_total

array([ 3, 17,  1, ...,  2,  2,  1])

In [11]:
from matplotlib import pyplot as plt
data = sum_col_total
bins = np.arange(0, 2000, 20)

plt.xlim([0, 2000])
plt.ylim([0, 2000])
plt.hist(data, bins = bins, alpha=0.5)
plt.show()

In [12]:
sum(sum_col_total>100)

4944

In [14]:
import heapq
N2 = 500
feature_index = sum_col_total.argsort()[-N2:][::-1]


In [15]:
feature_index

array([54382, 68129, 65701, 11525, 51944, 58273, 12900, 32580, 33948,
       13167, 42891, 38775, 44551, 55293, 62045, 67800, 56662, 65904,
       33860, 33570, 54080, 52152, 42754, 23263, 17785, 34214, 48344,
       56510, 18186, 12806, 52680, 60293, 46117, 12536, 66456, 69050,
       59816, 27682, 22065, 31393, 46643, 53781,  2889, 42768, 51479,
        2078,  5753, 30593,  8233, 21007, 23799, 54464,  6602, 54541,
       40365, 32928,   799, 26873, 39580, 34029, 51201, 54765, 19394,
       41378, 28232,   775, 12991, 56520, 58945, 47768, 39080, 41981,
        4749, 67500, 45230, 11181, 22849, 30291, 11869, 13534, 68479,
       58238, 11888, 68463, 29805,   850, 68197, 25873,  9545, 17908,
       38918, 39187, 18316, 51969, 40161, 37966, 63937,  9257, 29217,
       24101, 51964, 64935,  2618, 65238, 18579, 61174, 21040,  4389,
       18074, 32363, 24077, 47841, 58926, 11849, 10346, 45208, 26744,
        2311, 29272, 11885, 47496,  8156,  8678, 51302, 43983, 48339,
       50949, 68268,

In [16]:
feature_use = [feature_name[i] for i in feature_index]
feature_use

['not_wa',
 'wa',
 'thi',
 'food',
 'not_thi',
 'place',
 'good',
 'not_food',
 'not_good',
 'great',
 'not_order',
 'not_like',
 'not_place',
 'not_would',
 'servic',
 'veri',
 'order',
 'time',
 'not_go',
 'not_get',
 'not_veri',
 'not_time',
 'not_one',
 'not_back',
 'like',
 'not_great',
 'not_servic',
 'one',
 'love',
 'go',
 'not_tri',
 'restaur',
 'not_realli',
 'get',
 'tri',
 'would',
 'realli',
 'not_come',
 'not_also',
 'not_even',
 'not_restaur',
 'not_us',
 'best',
 'not_onli',
 'not_tast',
 'back',
 'chicken',
 'not_eat',
 'delici',
 'nice',
 'not_becaus',
 'not_wait',
 'come',
 'not_want',
 'not_menu',
 'not_fri',
 'alway',
 'not_chicken',
 'not_make',
 'not_got',
 'not_tabl',
 'not_well',
 'menu',
 'not_much',
 'not_could',
 'also',
 'got',
 'onli',
 'price',
 'not_sauc',
 'not_look',
 'not_nice',
 'came',
 'us',
 'not_price',
 'first',
 'not_ask',
 'not_drink',
 'fri',
 'ha',
 'went',
 'pizza',
 'friendli',
 'well',
 'not_dish',
 'amaz',
 'wait',
 'not_came',
 'eat',
 

In [23]:
X_simple = X_dataframe.iloc[:,feature_index]

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_simple, y, test_size=0.2, random_state=101)

In [25]:
X_train

54382  68129  65701  11525  51944  58273  12900  32580  33948  13167  \
1664       4      0      0      0      1      0      0      1      0      0   
92933      3      1      1      0      1      0      0      1      3      1   
46622      0      0      2      0      0      2      1      0      0      0   
50053      0      0      0      0      0      0      0      0      0      0   
34483      0      0      0      0      0      0      0      0      0      0   
81081      0      0      0      0      0      0      0      0      0      0   
31552      5      0      0      0      1      0      0      5      1      0   
72614      0      2      0      0      1      0      2      0      0      0   
63176      0      0      0      2      0      0      0      0      0      1   
79950      0      2      0      2      0      0      0      0      0      0   
95906      4      0      0      0      2      0      1      0      0      0   
56706      0      3      0      0      0      0      0      0      0      0   
87514      3      0      0      0      1      0      0      0      1      0   
97761      0      0      0      0      0      0      0      0      0      1   
82762      0      0      0      1      0      1      0      0      0      0   
3291       1      2      1      2      0      2      2      0      2      0   
18519      0      0      0      3      0      3      2      0      0      0   
802        4      0      1      0      0      0      0      0      0      0   
59569      0      1      1      0      0      1      0      0      0      0   
66961      0      5      0      2      0      0      2      0      0      1   
92306      0      1      1      0      1      1      0      0      1      0   
28454      0      2      0      1      0      0      1      0      0      0   
12808      1      0      1      0      0      0      0      0      0      0   
1090       0      0      0      0      0      0      1      0      0      0   
11040      0      0      0      1      0      1      0      3      0      0   
73343      0      3      0      0      0      0      0      0      0      1   
88970      0      1      0      1      0      1      0      0      0      0   
60990     11      0      1      0      4      0      0      6      2      0   
33785      0      0      1      0      2      1      0      0      0      0   
28892      5      0      0      0      2      0      0      1      1      0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
15436      0      3      0      2      0      0      0      0      0      0   
83193      0      1      1      1      0      0      0      0      1      0   
28488      0      0      0      0      0      0      1      0      0      0   
9772       0      1      0      0      0      0      0      0      0      1   
18491      0      1      2      1      0      1      0      0      0      0   
84851      0      0      1      0      0      1      1      0      0      0   
53619      0      0      0      0      3      0      0      0      0      0   
91642      1      0      0      0      2      0      0      0      0      0   
78447      4      0      1      0      1      1      0      2      2      0   
63315      9      3      1      0      2      1      1      4      1      0   
32817      0      2      0      1      0      0      1      0      0      0   
86493      1      2      0      0      0      1      0      0      0      0   
19566      0      6      1      0      0      0      0      0      0      5   
78556      2      2      0      0      5      0      0      0      0      0   
71996      0      1      0      1      0      0      1      0      0      0   
61173      0      0      0      0      0      1      0      0      0      0   
35391      0      0      1      0      0      0      2      0      0      0   
87684      2      0      0      0      0      0      2      2      0      0   
22056      0      0      0      0      0      0      0   

In [26]:
row_sum = X_train.apply(sum, axis=1)

In [28]:
sum(row_sum==0)

13

In [18]:
from scipy import sparse
sX_simple = sparse.csr_matrix(X_simple)

In [20]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
preds = nb.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, preds))
print('\n')
print(classification_report(y_test, preds))

[[ 397  220   70  252 1147]
 [ 291  310  163  327  873]
 [ 245  361  239  668 1402]
 [ 323  406  324 1114 3485]
 [ 419  264  166  806 5408]]


             precision    recall  f1-score   support

          1       0.24      0.19      0.21      2086
          2       0.20      0.16      0.18      1964
          3       0.25      0.08      0.12      2915
          4       0.35      0.20      0.25      5652
          5       0.44      0.77      0.56      7063

avg / total       0.34      0.38      0.33     19680



In [ ]:
sum((preds-y_test)**2)/len(preds)

2.908841463414634

In [ ]:
from sklearn import svm
clf = svm.SVC(decision_function_shape='ovo', kernel='linear')
clf.fit(X_train, y_train)  

In [ ]:
preds2 = clf.predict(X_test)
sum((preds2-y_test)**2)/len(preds)